=pod

=head1 Dex: CLI rolodex for the modern age



ability to add custom tags and query them w/ long options (e.g., dex 'kit kat' --discord)

basic input: dex [contact] to list details

=head2 DONE
help: dex OR dex -h
list all contacts: dex -l
contact exists?: dex -e [contact]
list platforms a contact is on: dex -o [contact]
update: dex -u [contact] -p [platform] -v [value]

store as json and serialize/deserialize to perl

=head2 TODO
add: dex -a [contact] -p [platform] -v [value]

delete: dex -d [contact] OR dex -d [contact] -p [platform]

pop into $editor to create new contacts

imports from thunderbird, gcontacts, etc

enforcing full uppercase

output anki cards of contact name and info

https://perldoc.perl.org/Getopt::Std
https://perldoc.perl.org/JSON::PP

=cut
